openapi: 3.0.0
info:
  title: ScholarMatch API - Mode Testing
  version: 1.0.0
  description: Dokumentasi API untuk ScholarMatch - Platform Informasi dan Pencarian Beasiswa

servers:
  - url: http://localhost:3100

paths:
  /api/auth/register:
    post:
      tags:
        - Auth
      summary: Register user baru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User berhasil terdaftar
        '400':
          description: Email sudah digunakan
        '500':
          description: Server error

  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login berhasil
        '401':
          description: Email atau Password salah
        '500':
          description: Server error

  /api/scholarships:
    get:
      tags:
        - Scholarship
      summary: Mendapatkan semua data beasiswa
      responses:
        '200':
          description: Sukses mendapatkan semua beasiswa

    post:
      tags:
        - Scholarship
      summary: Tambah beasiswa (Admin Only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - provider
                - deadline
                - description
                - requirements
                - documents
                - benefits
              properties:
                name:
                  type: string
                provider:
                  type: string
                deadline:
                  type: string
                  format: date
                description:
                  type: string
                requirements:
                  type: string
                documents:
                  type: string
                benefit:
                  type: string
      responses:
        '201':
          description: Beasiswa ditambahkan
        '403':
          description: Hanya admin yang dapat menambahkan
        '500':
          description: Server error

  /api/scholarships/{id}:
    get:
      tags:
        - Scholarship
      summary: Mendapatkan beasiswa berdasarkan ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Berhasil mendapatkan data
        '404':
          description: Beasiswa tidak ditemukan

    put:
      tags:
        - Scholarship
      summary: Update beasiswa berdasarkan ID (Admin Only)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                provider:
                  type: string
                deadline:
                  type: string
                  format: date
                description:
                  type: string
                requirements:
                  type: string
                documents:
                  type: string
                benefit:
                  type: string
      responses:
        '200':
          description: Berhasil diperbarui
        '403':
          description: Hanya admin
        '404':
          description: Beasiswa tidak ditemukan

    delete:
      tags:
        - Scholarship
      summary: Hapus beasiswa (Admin Only)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Beasiswa dihapus
        '403':
          description: Akses ditolak
        '404':
          description: Tidak ditemukan

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT